# Generated by Django 6.0.1 on 2026-02-02 15:44

import apps.questions.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this object",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when this object was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when this object was last updated"
                    ),
                ),
                (
                    "text",
                    models.JSONField(
                        help_text="Question text in multiple languages (JSON)",
                        validators=[apps.questions.models.validate_multilingual_text],
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="Subject this question belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questions",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this object",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when this object was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when this object was last updated"
                    ),
                ),
                (
                    "text",
                    models.JSONField(
                        help_text="Choice text in multiple languages (JSON)",
                        validators=[apps.questions.models.validate_multilingual_text],
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of choice (0 = correct answer)"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        help_text="Question this choice belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Choice",
                "verbose_name_plural": "Choices",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["subject", "-created_at"], name="questions_q_subject_2b329b_idx"
            ),
        ),
    ]
