# Generated by Django 6.0.1 on 2026-02-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="title",
            field=models.CharField(
                default="no title",
                help_text="Short title to identify this question",
                max_length=200,
            ),
        ),
    ]
