# Generated by Django 6.0.1 on 2026-02-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_question_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="variables",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Variable definitions for parametric questions (JSON)",
                null=True,
            ),
        ),
    ]
