# Generated by Django 6.0.1 on 2026-02-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0003_question_variables"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="validation_rules",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of validation expressions (e.g., ['a > b', 'a + b > c'])",
            ),
        ),
    ]
