# Generated by Django 6.0.1 on 2026-02-03 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0006_rename_choice_question_to_template"),
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="questiontemplate",
            new_name="questions_q_subject_d74872_idx",
            old_name="questions_q_subject_2b329b_idx",
        ),
        migrations.AlterField(
            model_name="choice",
            name="template",
            field=models.ForeignKey(
                help_text="Question template this choice belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="questions.questiontemplate",
            ),
        ),
        migrations.AlterField(
            model_name="questiontemplate",
            name="subject",
            field=models.ForeignKey(
                help_text="Subject this question template belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="question_templates",
                to="subjects.subject",
            ),
        ),
        migrations.AlterField(
            model_name="questiontemplate",
            name="title",
            field=models.CharField(
                default="",
                help_text="Short title to identify this question template",
                max_length=200,
            ),
        ),
    ]
