# Generated by Django 6.0.1 on 2026-02-12 14:09

import apps.questions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "questions",
            "0007_rename_questions_q_subject_2b329b_idx_questions_q_subject_d74872_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="questiontemplate",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Template",
                "verbose_name_plural": "Templates",
            },
        ),
        migrations.AddField(
            model_name="questiontemplate",
            name="tags",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Comma-separated tags (e.g. easy, exam-2024, review)",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="questiontemplate",
            name="text",
            field=models.JSONField(
                help_text="Template text in multiple languages (JSON)",
                validators=[apps.questions.models.validate_multilingual_text],
            ),
        ),
    ]
