# Generated by Django 6.0.1 on 2026-02-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0008_alter_questiontemplate_options_questiontemplate_tags_and_more"),
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questiontemplate",
            name="state",
            field=models.CharField(
                choices=[("draft", "Draft"), ("completed", "Completed"), ("reviewed", "Reviewed")],
                default="draft",
                help_text="Lifecycle state: draft, completed, or reviewed",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="questiontemplate",
            index=models.Index(fields=["state"], name="questions_q_state_017ad7_idx"),
        ),
    ]
