# Generated by Django 6.0.1 on 2026-02-02 14:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this object",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when this object was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when this object was last updated"
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the subject or topic", max_length=200),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Optional description of the subject"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent subject (leave empty for root-level subjects)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("parent", "name"), name="unique_subject_name_per_parent"
                    )
                ],
            },
        ),
    ]
