# Generated by Django 6.0.1 on 2026-02-03 22:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "questions",
            "0007_rename_questions_q_subject_2b329b_idx_questions_q_subject_d74872_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this object",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Exam",
                "verbose_name_plural": "Exams",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuestionPool",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this object",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when this object was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when this object was last updated"
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pools",
                        to="exams.exam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question Pool",
                "verbose_name_plural": "Question Pools",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="QuestionPoolTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this object",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when this object was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when this object was last updated"
                    ),
                ),
                (
                    "number_of_versions",
                    models.PositiveIntegerField(
                        default=1, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pool_templates",
                        to="exams.questionpool",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pool_memberships",
                        to="questions.questiontemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question Pool Template",
                "verbose_name_plural": "Question Pool Templates",
                "unique_together": {("pool", "template")},
            },
        ),
        migrations.AddField(
            model_name="questionpool",
            name="question_templates",
            field=models.ManyToManyField(
                related_name="pools",
                through="exams.QuestionPoolTemplate",
                to="questions.questiontemplate",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="questionpool",
            unique_together={("exam", "order")},
        ),
    ]
