# Generated by Django 6.0.1 on 2026-02-05 07:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="grading_mode",
            field=models.CharField(
                choices=[("single", "Single Choice"), ("multi", "Multiple Choice")],
                default="single",
                help_text="Single Choice: Student can only choose one correct answer. Multiple Choice: Student can choose multiple correct answers.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="questionpool",
            name="default_grade",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.0"),
                help_text="Point value for questions in this pool (default: 1.0)",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.1"))],
            ),
        ),
    ]
